site:
  name: Servicio de Reclutamiento Militar
  site: 'https://reclutamiento-ejercito.netlify.app/'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: orcPxI47GSa-cRvY11tUe6iGg2IO_RPvnA1q95iEM3M

# Default SEO metadata
metadata:
  title:
    default: Servicio de Reclutamiento Militar
    template: 'Servicio de Reclutamiento Militar'
  description: "Sitio Web para Registros en el Servicio Militar del Ejército del Perú"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Servicio de Reclutamiento Militar
    images:
      - url: 'reclutamiento-ejercito.netlify.app/assets/images/banner.jpg'
        width: 1200
        height: 628
    type: website

i18n:
  language: en
  textDirection: ltr

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
